from dataclasses import dataclass
from typing import Literal, Protocol


@dataclass(frozen=True)
class ExportedProfile:
    format: Literal["deeplink", "toml"]
    content: str
    media_type: str


class TrustTunnelExporter(Protocol):
    def export(self, username: str, address: str,
               format: Literal["deeplink", "toml"]) -> ExportedProfile: ...


class FakeTrustTunnelExporter:
    """Sandbox substitute for official CLI. Its marker is intentionally not a real tt:// format."""

    def export(self, username: str, address: str,
               format: Literal["deeplink", "toml"]) -> ExportedProfile:
        if format == "deeplink":
            return ExportedProfile(format, f"sandbox-profile:{username}@{address}", "text/plain")
        return ExportedProfile(
            format,
            f'# Generated by FakeTrustTunnelExporter\nserver = "{address}"\nusername = "{username}"\n',
            "application/toml",
        )
