from dataclasses import dataclass
from typing import Literal, Protocol

from tunnelui.agent.client import AgentClientError, LinuxAgentClient
from tunnelui.domain.errors import DomainError


@dataclass(frozen=True)
class ExportedProfile:
    format: Literal["deeplink", "toml"]
    content: str
    media_type: str


class TrustTunnelExporter(Protocol):
    def export(self, username: str, address: str,
               format: Literal["deeplink", "toml"]) -> ExportedProfile: ...


class FakeTrustTunnelExporter:
    """Sandbox substitute for official CLI. Its marker is intentionally not a real tt:// format."""

    def export(self, username: str, address: str,
               format: Literal["deeplink", "toml"]) -> ExportedProfile:
        if format == "deeplink":
            return ExportedProfile(format, f"sandbox-profile:{username}@{address}", "text/plain")
        return ExportedProfile(
            format,
            f'# Generated by FakeTrustTunnelExporter\nserver = "{address}"\nusername = "{username}"\n',
            "application/toml",
        )


class AgentTrustTunnelExporter:
    """Profile adapter; public address and binary argv are resolved inside the agent."""

    def __init__(self, client: LinuxAgentClient, managed_id: str):
        self.client = client
        self.managed_id = managed_id

    def export(self, username: str, address: str,
               format: Literal["deeplink", "toml"]) -> ExportedProfile:
        del address
        try:
            content = self.client.export(self.managed_id, username, format).decode("utf-8")
        except (AgentClientError, UnicodeDecodeError) as error:
            code = error.code if isinstance(error, AgentClientError) else "profile_export_invalid"
            raise DomainError(code) from None
        media = "text/plain" if format == "deeplink" else "application/toml"
        return ExportedProfile(format, content, media)
