import { expect, test } from '@playwright/test';

test('admin: login, client CRUD, duplicate, audit, logout and responsive themes', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.goto('/');
  await page.getByLabel('Имя администратора').fill('test-admin');
  await page.getByLabel('Пароль', { exact: true }).fill('test-only-password');
  await page.getByRole('button', { name: 'Войти', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Входящие' })).toBeVisible();
  await expect(page.getByText('Нет импортированных входящих')).toBeVisible();
  await page.screenshot({ path: 'test-results/inbounds-desktop-light.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('link', { name: 'Клиенты', exact: true }).click();
  await page.getByRole('button', { name: 'Добавить клиента' }).click();
  await page.getByLabel('Username', { exact: true }).fill('test-ivan');
  await page.getByLabel('Отображаемое имя').fill('Иван · тестовая запись');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.getByRole('cell', { name: 'test-ivan', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Добавить клиента' }).click();
  await page.getByLabel('Username', { exact: true }).fill('test-ivan');
  await page.getByLabel('Отображаемое имя').fill('Дубликат');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.getByText('Такой username уже существует. Укажите другой.')).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Действия: test-ivan' }).click();
  await page.getByRole('menuitem', { name: 'Редактировать' }).click();
  await page.getByLabel('Отображаемое имя').fill('Очень длинное имя клиента для проверки отображения в таблице и редакторе');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.getByRole('cell', { name: /Очень длинное/ })).toBeVisible();
  await page.getByRole('button', { name: 'Тёмная тема' }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.screenshot({ path: 'test-results/clients-desktop-dark.png', fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Открыть меню' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/clients-mobile-dark.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Открыть меню' }).click();
  await page.getByRole('link', { name: 'Аудит', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Аудит' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Создан глобальный клиент', exact: true })).toBeVisible();
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.getByRole('complementary').getByRole('link', { name: 'Клиенты', exact: true }).click();
  await page.getByRole('button', { name: 'Действия: test-ivan' }).click();
  await page.getByRole('menuitem', { name: 'Удалить', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Удалить', exact: true }).click();
  await expect(page.getByRole('cell', { name: 'test-ivan', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Выйти', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Вход в панель' })).toBeVisible();
  expect(errors).toEqual([]);
});

test('mobile login and visible network failure', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Вход в панель' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/login-mobile-light.png', fullPage: true });
  await page.route('**/api/auth/login', route => route.abort());
  await page.getByLabel('Имя администратора').fill('test-admin');
  await page.getByLabel('Пароль', { exact: true }).fill('test-only-password');
  await page.getByRole('button', { name: 'Войти', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Нет связи с панелью');
});
